version: "3.9"
services:
  mysql:
    container_name: mysql_container
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test_db
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./config-file.cnf:/etc/mysql/conf.d/config-file.cnf
      - ./test_data:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - mysql

networks:
  mysql:
    driver: bridge
