version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:13.3
    environment:
      POSTGRES_DB: "test_database"
#      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
      - ./test_data:/docker-entrypoint-initdb.d
      - ./pgbackup:/pgbackup
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
